development:
  strategy: oauth
  oauth_consumer_key: qzZeVnwqkxW3cyc1mw
  oauth_consumer_secret: t0Tm0NIhQ8UFwwPwd7YhDXK32U92KFTHWD1m7TrpI
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authorize"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://help-me-hackers/oauth_callback"
  ca_file: <%= File.join(RAILS_ENV, 'config', 'twitter.pem') %>
  bitly_api_username: komagata
  bitly_api_key: R_6b987056a90c7e33edefc97564e57af8
test:
  strategy: oauth
  oauth_consumer_key: testkey
  oauth_consumer_secret: testsecret
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authorize"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://help-me-hackers/oauth_callback"
  ca_file: <%= File.join(RAILS_ENV, 'config', 'twitter.pem') %>
  bitly_api_username: komagata
  bitly_api_key: R_6b987056a90c7e33edefc97564e57af8
production:
  strategy: oauth
  oauth_consumer_key: qzZeVnwqkxW3cyc1mw
  oauth_consumer_secret: t0Tm0NIhQ8UFwwPwd7YhDXK32U92KFTHWD1m7TrpI
  authorize_path: "/oauth/authorize"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://help-me-hackers.com/oauth_callback"
  ca_file: <%= File.join(RAILS_ENV, 'config', 'twitter.pem') %>
  bitly_api_username: komagata
  bitly_api_key: R_6b987056a90c7e33edefc97564e57af8
